Registration :
- [OK] users can register

- [OK] but sending confirmation email fails 
	(org.springframework.mail.MailSendException: Failed messages:
com.sun.mail.smtp.SMTPSendFailedException: 554 Message rejected: Email
address is not verified.)
	Solution : Make a Amazon SES Address Verification Request

- [FIXED] Activate a user fails
	No signature of method: spine.SpineService.activateUser() is applicable
for argument types: (java.lang.String) values: [pj82491@gmail.com]
Possible solutions: activateUser(spine.User) 

- [FIXED] when user is registred but not active the error message on the
login page was "Invalid user/password combination" instead of "User not
active!"

- update profile picture [OK]

- [FIXED] error when logging with user that does not exists (because of
a null object)




Search : 

- [OK]Search tag for the user network

- [TO FIX] Search tag for outside network

- Badges are now indexed

- [NEED MORE TESTS] Search for badges should work

- [TO FIX] Search badge "The Operator" will not work. System will search
"The" or "Operator"... Cannot be solved easily without breaking multi
tag search

- [CHANGED] When no filter (search) is applied do not query the
super_index for expected results (which did not make sense)

- [TO FIX] Tests testQueryForNeighbourNodes1 and
testQueryForNeighbourNodes2 are borken. Looks like it's because of the
ordering

- [FIXED] Search does not propagate through infinite pagination
(scrolling)

- [OK] When searching, we don't see the query. Not a bug but a feature
which I think it make sense to implement. So I did it.